import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import { Handjet } from "next/font/google";
import LenisProvider from "../app/Components/LenisProvider";

import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const handjet = Handjet({
  subsets: ["latin"],
  weight: ["500", "700"],
  variable: "--font-handjet",
});

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["200", "300", "400", "500", "600", "700"],
  variable: "--font-poppins",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={` h-full antialiased ${handjet.variable} ${poppins.variable}`}
    >
      <body className="min-h-full flex flex-col">
                <LenisProvider>

        {children}
                </LenisProvider>

        </body>
    </html>
  );
}
